require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestScaffoldsController do

  # This should return the minimal set of attributes required to create a valid
  # TestScaffold. As you add validations to TestScaffold, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestScaffoldsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all test_scaffolds as @test_scaffolds" do
      test_scaffold = TestScaffold.create! valid_attributes
      get :index, {}, valid_session
      assigns(:test_scaffolds).should eq([test_scaffold])
    end
  end

  describe "GET show" do
    it "assigns the requested test_scaffold as @test_scaffold" do
      test_scaffold = TestScaffold.create! valid_attributes
      get :show, {:id => test_scaffold.to_param}, valid_session
      assigns(:test_scaffold).should eq(test_scaffold)
    end
  end

  describe "GET new" do
    it "assigns a new test_scaffold as @test_scaffold" do
      get :new, {}, valid_session
      assigns(:test_scaffold).should be_a_new(TestScaffold)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_scaffold as @test_scaffold" do
      test_scaffold = TestScaffold.create! valid_attributes
      get :edit, {:id => test_scaffold.to_param}, valid_session
      assigns(:test_scaffold).should eq(test_scaffold)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TestScaffold" do
        expect {
          post :create, {:test_scaffold => valid_attributes}, valid_session
        }.to change(TestScaffold, :count).by(1)
      end

      it "assigns a newly created test_scaffold as @test_scaffold" do
        post :create, {:test_scaffold => valid_attributes}, valid_session
        assigns(:test_scaffold).should be_a(TestScaffold)
        assigns(:test_scaffold).should be_persisted
      end

      it "redirects to the created test_scaffold" do
        post :create, {:test_scaffold => valid_attributes}, valid_session
        response.should redirect_to(TestScaffold.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_scaffold as @test_scaffold" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestScaffold.any_instance.stub(:save).and_return(false)
        post :create, {:test_scaffold => {  }}, valid_session
        assigns(:test_scaffold).should be_a_new(TestScaffold)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestScaffold.any_instance.stub(:save).and_return(false)
        post :create, {:test_scaffold => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_scaffold" do
        test_scaffold = TestScaffold.create! valid_attributes
        # Assuming there are no other test_scaffolds in the database, this
        # specifies that the TestScaffold created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TestScaffold.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => test_scaffold.to_param, :test_scaffold => { "these" => "params" }}, valid_session
      end

      it "assigns the requested test_scaffold as @test_scaffold" do
        test_scaffold = TestScaffold.create! valid_attributes
        put :update, {:id => test_scaffold.to_param, :test_scaffold => valid_attributes}, valid_session
        assigns(:test_scaffold).should eq(test_scaffold)
      end

      it "redirects to the test_scaffold" do
        test_scaffold = TestScaffold.create! valid_attributes
        put :update, {:id => test_scaffold.to_param, :test_scaffold => valid_attributes}, valid_session
        response.should redirect_to(test_scaffold)
      end
    end

    describe "with invalid params" do
      it "assigns the test_scaffold as @test_scaffold" do
        test_scaffold = TestScaffold.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestScaffold.any_instance.stub(:save).and_return(false)
        put :update, {:id => test_scaffold.to_param, :test_scaffold => {  }}, valid_session
        assigns(:test_scaffold).should eq(test_scaffold)
      end

      it "re-renders the 'edit' template" do
        test_scaffold = TestScaffold.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestScaffold.any_instance.stub(:save).and_return(false)
        put :update, {:id => test_scaffold.to_param, :test_scaffold => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_scaffold" do
      test_scaffold = TestScaffold.create! valid_attributes
      expect {
        delete :destroy, {:id => test_scaffold.to_param}, valid_session
      }.to change(TestScaffold, :count).by(-1)
    end

    it "redirects to the test_scaffolds list" do
      test_scaffold = TestScaffold.create! valid_attributes
      delete :destroy, {:id => test_scaffold.to_param}, valid_session
      response.should redirect_to(test_scaffolds_url)
    end
  end

end
